# Production training configuration
defaults:
  - model: phi4_mini
  - training: production
  - data: medical
  - inference: default
  - _self_

mode: train
seed: 816
output_dir: ./checkpoints/production-model