# @package _global_
training:
  batch_size: 1
  learning_rate: 2e-4
  max_steps: 10
  validate_steps: 5
  gradient_accumulation_steps: 1
  warmup_steps: 2
  logging_steps: 1
  save_steps: 5
  eval_steps: 5
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 3
    metric: eval_loss
    
  # Optimizer settings
  optimizer:
    type: adamw
    weight_decay: 0.01
    
  # Scheduler settings
  scheduler:
    type: cosine
    warmup_ratio: 0.03