# @package _global_
training:
  batch_size: 1
  learning_rate: 2e-4
  
  # Training duration - use either max_steps OR num_epochs
  # When both are specified, max_steps takes precedence
  max_steps: null  # null means use epochs instead
  num_epochs: 3    # Number of epochs to train
  
  validate_steps: 5
  gradient_accumulation_steps: 1
  warmup_steps: 2
  logging_steps: 1
  save_steps: 5
  eval_steps: 5
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 3
    metric: eval_loss
    
  # Optimizer settings
  optimizer:
    type: adamw
    weight_decay: 0.01
    
  # Scheduler settings
  scheduler:
    type: cosine
    warmup_ratio: 0.03