# @package _global_
inference:
  adapter_path: ${output_dir}/lora_adapter
  interactive: true
  demo_question: "What are the latest treatment guidelines for hypertension?"
  
  # Memory and device settings
  memory:
    offload_dir: "./offload_tmp"
    max_memory:
      gpu: "6GiB"
      cpu: "30GiB"
    dtype: "float16"
    low_cpu_mem_usage: true
  
  # Generation parameters
  generation:
    max_new_tokens: 512
    temperature: 0.6
    top_p: 0.9
    do_sample: true
    
