# @package _global_
inference:
  adapter_path: ${output_dir}/lora_adapter
  interactive: true
  demo_question: "What are the latest treatment guidelines for hypertension?"
  
  # Generation parameters
  generation:
    max_new_tokens: 512
    temperature: 0.7
    top_p: 0.9
    do_sample: true
    
