"""Legacy configuration settings - now using Hydra configuration."""

import os
from typing import Dict, List, Any

# Legacy constants for backward compatibility
# These are now handled by Hydra configuration files in conf/

# Default fallback values if needed by legacy code
SEED = 816
BASE_MODEL = "microsoft/Phi-4-mini-instruct"
TRAIN_FILE = "./data/my_custom_data.jsonl"
OUTPUT_DIR = "./checkpoints/llama3-lora-med"
MAX_LENGTH = 512
BATCH_SIZE = 1
LEARNING_RATE = 2e-4
MAX_STEPS = 10
VALIDATE_STEPS = 5

# Available tools for function calling (now defined in conf/inference/default.yaml)
TOOLS = [
    {
        "name": "search_internet",
        "description": "Search the internet for current medical information, research, and clinical guidelines",
        "parameters": {
            "query": {
                "description": "The medical search query",
                "type": "str"
            },
            "num_results": {
                "description": "Number of search results to return",
                "type": "int",
                "default": 5
            }
        }
    },
    {
        "name": "retrieve_clinical_guidelines",
        "description": "Retrieve clinical guidelines and best practices for specific conditions.",
        "parameters": {
            "condition": {
                "description": "The medical condition to retrieve guidelines for",
                "type": "str"
            },
            "guideline_source": {
                "description": "Source of guidelines (e.g., 'NICE', 'AHA', 'CDC', 'WHO', 'JAMA', 'NEJM', 'American Cancer Society')",
                "type": "str",
                "default": "general"
            }
        }
    }
]

# System prompt for medical assistant (now defined in conf/data/medical.yaml)
SYSTEM_PROMPT = (
    "You are a careful medical assistant with access to tools for finding current information. "
    "You can search the internet for recent medical research and clinical guidelines. "
    "Reason step by step, cite sources when available, and avoid guessing beyond provided information. "
    "Your primary function is to not harm. If you are unsure, tell the user you don't know or will search for information. "
    "Use tools proactively when questions require current information or specific guidelines. "
    "Always end the conversation with 'This response was generated by AI. "
    "Please check with professional medical practitioners to confirm the results are safe and appropriate.'"
)